# Generated by Django 4.2.1 on 2023-06-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_remove_myuser_date_of_birth_myuser_mobile_myuser_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='USER_TYPE',
            field=models.IntegerField(choices=[(1, 'Restaurent'), (2, 'Customer'), (3, 'Driver')], default=1),
        ),
        migrations.AddField(
            model_name='myuser',
            name='otp_expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
